
#ifndef AGILOR_CLUSTER_GLOBAL_DEFINITIONS_
#define AGILOR_CLUSTER_GLOBAL_DEFINITIONS_

#define RS_OK									0
#define RS_ERROR								-1
#define RS_FAIL									-2
#define RS_TIME_OUT								-3

#define RS_INVALID_SOCKET							-10
#define RS_SOCKET_BUFFER_FULL						-11
#define RS_SOCKET_DISCONNECTED						-12

#define RS_TAG_REACH_MAX_COUNT						-100
#define RS_TAG_FIND_UNUSED_TAG_ID_FAIL				-101
#define RS_INVALID_TAG_ID							-102
#define RS_TAG_ALREADY_EXIST						-103		
#define RS_INVALID_TAG_NAME							-104
#define RS_INVALID_DEVICE_NAME						-105
#define RS_DEVICE_REACH_MAX_COUNT					-106
#define RS_DEVICE_ALREADY_EXIST						-107
#define RS_DEVICE_FIND_UNUSED_DEVICE_ID_FAIL		-108

#define RS_DATA_DISTRIBUTION_OPEN_FILE_ERROR		-200
#define RS_DATA_DISTRIBUTION_FILE_DESCRIPTION_ERROR	-201
#define RS_DEVICE_INFO_OPEN_FILE_ERROR				-202
#define RS_DEVICE_INFO_FILE_DESCRIPTION_ERROR		-203

#define RS_SERVICE_NOT_STARTED						-300
#define RS_SERVICE_NOT_STOPPED						-301

#define RS_CLIENT_EXCEED_MAX_CONNECTION_COUNT		-400

#define RS_DEVICE_EXCEED_MAX_CONNECTION_COUNT		-500

#define SOCKET_STATUS_DISCONNECTED				0
#define SOCKET_STATUS_CONNECTED					1
#define SOCKET_STATUS_CONNECTING				2

#define AGILOR_NODE_STATUS_BUSY					10
#define AGILOR_NODE_STATUS_WAIT					11

#define FILE_PATH_MAX_LENGTH					1024
#define DATA_DISTRIBUTION_FILE_NAME				"DataDistribution.cdd"
#define DEVICE_INFO_FILE_NAME					"DeviceInfo.cdd"
#define WRITE_FILE_BUFFER_SIZE					16 * 1024 * 1024

#define TAG_DISTRIBUTION_INFO_MODIFIED_FLAG		1
#define TAG_DISTRIBUTION_INFO_MANAGER_ADD_FOR_AGILOR_NODE_FLAG		2
#define TAG_DISTRIBUTION_INFO_MANAGER_ADD_FOR_STANDBY_NODE_FLAG		4

#define TAG_TYPE_NORMAL							1
#define TAG_TYPE_DEVICE_STATUS					2

const long	DEVICE_STATUS_TAG_NAME_PREFIX_LEN = 20;
const char	DEVICE_STATUS_TAG_NAME_PREFIX[DEVICE_STATUS_TAG_NAME_PREFIX_LEN + 1] = "%#_ClusterDevStatus_";


#define DATA_DISTRIBUTION_FILE_DESCRIPTION			"Agilor Cluster Data Distribution File"
#define DATA_DISTRIBUTION_FILE_VERSION				"v1.000000000"

#define DEVICE_INFO_FILE_DESCRIPTION				"Agilor Cluster Device Info File"
#define DEVICE_INFO_FILE_VERSION					"v1.000000000"

#define	CLUSTER_SERVICE_STATUS_UNKNOWN								0
#define CLUSTER_SERVICE_STATUS_STARTED								1
#define CLUSTER_SERVICE_STATUS_STOPPED								2

#define TO_AGILOR_NODE												1
#define TO_STANDBY_AGILOR_NODE										2

#define QUERY_TYPE_NORMAL											0
#define QUERY_TYPE_QUERY_RT											1
#define QUERY_TYPE_QUERY_HIS										2

const int STR_LEN_REG = 32;

const char REG_KEY_START[STR_LEN_REG]				= "SOFTWARE";
const char REG_KEY_COMPANY_NAME[STR_LEN_REG]		= "ISCAS";
const char REG_KEY_PRODUCT_NAME[STR_LEN_REG]		= "AgilorCluster";
const char REG_KEY_VERSION[STR_LEN_REG]				= "1.0";

const char REG_VALUE_APPPATH[STR_LEN_REG]			= "AppPath";

#define AGILOR_NODES_INI_FILE_NAME					"AgilorNodes.ini"

#define IP_ADDRESS_MAX_LENGTH						256

#endif
